In [1]:
# Known probabilities
pi_a = 0.78  # P(Y = A)
pi_b = 0.22  # P(Y = B)

P_X_given_A_1 = 0.35  # P(X = 1 | Y = A)
P_X_given_B_1 = 0.61  # P(X = 1 | Y = B)

# Calculate P(X = 0 | Y = A) and P(X = 0 | Y = B)
P_X_given_A_0 = 1 - P_X_given_A_1
P_X_given_B_0 = 1 - P_X_given_B_1

# Total probability for P(X = 0) and P(X = 1)
P_X_0 = (P_X_given_A_0 * pi_a) + (P_X_given_B_0 * pi_b)
P_X_1 = (P_X_given_A_1 * pi_a) + (P_X_given_B_1 * pi_b)

# Conditional probabilities using Bayes' Theorem
P_Y_A_given_X_0 = (P_X_given_A_0 * pi_a) / P_X_0
P_Y_B_given_X_0 = (P_X_given_B_0 * pi_b) / P_X_0

P_Y_A_given_X_1 = (P_X_given_A_1 * pi_a) / P_X_1
P_Y_B_given_X_1 = (P_X_given_B_1 * pi_b) / P_X_1

P_Y_A_given_X_0, P_Y_B_given_X_0, P_Y_A_given_X_1, P_Y_B_given_X_1


(0.8552631578947368,
 0.14473684210526316,
 0.6704322200392927,
 0.3295677799607073)

In [1]:
import math
# Parameters for the classes
params = {
    "A": {"mu": 2, "sigma": 1, "prior": 0.58},
    "B": {"mu": 3, "sigma": 2, "prior": 0.38},
    "C": {"mu": 6, "sigma": 2, "prior": 0.04},
}

# Observed values
x_values = [2.57, 4.71, 4.12]

def likelihood(x, mu, sigma):
    return (1 / (math.sqrt(2 * math.pi) * sigma)) * math.exp(-((x - mu) ** 2) / (2 * sigma**2))

# Compute the Bayes Classifier output
def bayes_classifier(x, params):
    # Compute scores for each class
    scores = {
        label: likelihood(x, params[label]["mu"], params[label]["sigma"]) * params[label]["prior"]
        for label in params
    }
    # Return the class with the highest score
    return max(scores, key=scores.get), scores

# Evaluate classifier for each observed x
classifier_results = {x: bayes_classifier(x, params) for x in x_values}
classifier_results

{2.57: ('A',
  {'A': 0.19669210165843148,
   'B': 0.07406721849637803,
   'C': 0.0018334166359873262}),
 4.71: ('B',
  {'A': 0.005882839598976504,
   'B': 0.05259247448894991,
   'C': 0.006480393542253461}),
 4.12: ('B',
  {'A': 0.02445634203782678,
   'B': 0.064798699839767,
   'C': 0.005129425888512407})}

In [2]:
# Re-importing necessary libraries and recalculating due to execution environment reset
import numpy as np
from scipy.stats import multivariate_normal

# Given data
pi_A = 0.78  # P(Y = A)
pi_B = 0.22  # P(Y = B)

mu_A = np.array([4.2, 4.6, 5.6])
mu_B = np.array([2.7, 5.0, 8.8])

Sigma_A = np.diag([9, 4, 4])
Sigma_B = np.diag([9, 4, 4])

X = np.array([2.1, 4.0, 8.4])  # Data point to evaluate

# Multivariate Normal PDF
p_X_given_A = multivariate_normal.pdf(X, mean=mu_A, cov=Sigma_A)
p_X_given_B = multivariate_normal.pdf(X, mean=mu_B, cov=Sigma_B)

# Total probability P(X)
p_X = p_X_given_A * pi_A + p_X_given_B * pi_B

# Posterior probabilities using Bayes' theorem
p_A_given_X = (p_X_given_A * pi_A) / p_X
p_B_given_X = (p_X_given_B * pi_B) / p_X

p_A_given_X, p_B_given_X


(0.540080411814865, 0.45991958818513495)

In [ ]:
import numpy as np
import pandas as pd
from scipy.stats import norm

x_1 = np.array([4.78, 3.51, 7.88, 5.32, 4.94, 8.52, 8.52, 8.02, 8.31, 2.44, 6.83, 7.16, 8.68, 8.13, 8.96, 4.84, 5.08, 4.58, 4.45, 4., 7.95, 3.65, 4.79, 5.48, 4.07, 4.06, 8.85, 4.36, 4.06, 6.51, 5.16, 6.99, 4.37, 4.56, 5.04, 5.96, 2.4, 8.7, 3.59, 4.93, 7.18, 2.86, 3.5, 4.67, 7.91, 6.35, 7.18, 5.29, 5.57, 3.68])
x_2 = x_2 = np.array([4.08, 3.96, 6.23, 6.26, 5.92, 7.34, 6.64, 7.92, 6.31, 5.29, 7.23, 6.29, 7.39, 6.35, 6.28, 4.98, 3.49, 4.45, 4.51, 4.35, 5.13, 5.15, 3.37, 3.67, 3.42, 4.63, 4.99, 2.4, 4.24, 4.8, 5.67, 6.24, 4.51, 5.28, 4.35, 5.28, 4.92, 5.12, 2.95, 5.73, 7.34, 4.25, 3.62, 5.26, 5.76, 6.07, 6.73, 4.6, 4.96, 4.78])
A, B = "A", "B"
y = y = np.array([A, A, B, A, A, B, B, B, B, A, B, B, B, B, B, A, A, A, A, A, B, A, A, A, A, A, B, A, A, A, A, B, A, A, A, A, A, B, A, A, B, A, A, A, B, B, B, A, A, A])
df = pd.DataFrame({'y': y, 'x_1': x_1, 'x_2': x_2})

data_A = df[df['y'] == A]
data_B = df[df['y'] == B]

P_A = len(data_A) / len(df)
P_B = len(data_B) / len(df)

# Means and stds
means_A = data_A[['x_1', 'x_2']].mean()
std_devs_A = data_A[['x_1', 'x_2']].std(ddof=0)  # Standard deviation not VARIANCE!!!!

means_B = data_B[['x_1', 'x_2']].mean()
std_devs_B = data_B[['x_1', 'x_2']].std(ddof=0) # Standard deviation not VARIANCE!!!

# change this to the x1 and x2
points = [(4.65, 6.73), (4.38, 7.67)]

posteriors = []
def compute_posterior(x1, x2):
    likelihood_A = norm.pdf(x1, means_A['x_1'], std_devs_A['x_1']) * norm.pdf(x2, means_A['x_2'], std_devs_A['x_2'])
    likelihood_B = norm.pdf(x1, means_B['x_1'], std_devs_B['x_1']) * norm.pdf(x2, means_B['x_2'], std_devs_B['x_2'])
    total_probability = (P_A * likelihood_A) + (P_B * likelihood_B)
    posterior_A = (P_A * likelihood_A) / total_probability
    posterior_B = (P_B * likelihood_B) / total_probability
    return posterior_A, posterior_B

for point in points:
    posteriors.append(compute_posterior(point[0], point[1]))

# Report results
print("Class Priors:")
print(f"n_A: {len(data_A)}")
print(f"n_B: {len(data_B)}")
print(f"P(A): {P_A}")
print(f"P(B): {P_B}\n")

print("Means and Variances for Class A:")
print(f"\u03BC_x1|Y=A: {means_A['x_1']}")
print(f"\u03C3^2_x1|Y=A: {std_devs_A['x_1']}")
print(f"\u03BC_x2|Y=A: {means_A['x_2']}")
print(f"\u03C3^2_x2|Y=A: {std_devs_A['x_2']}")

print("\nMeans and Variances for Class B:")
print(f"\u03BC_x1|Y=B: {means_B['x_1']}")
print(f"\u03C3^2_x1|Y=B: {std_devs_B['x_1']}")
print(f"\u03BC_x2|Y=B: {means_B['x_2']}")
print(f"\u03C3^2_x2|Y=B: {std_devs_B['x_2']}")

for i, point in enumerate(points):
    print(f"\nPosteriors for point {point}:")
    print(f"P(A | x): {posteriors[i][0]}")
    print(f"P(B | x): {posteriors[i][1]}")


Class Priors:
n_A: 32
n_B: 18
P(A): 0.64
P(B): 0.36

Means and Variances for Class A:
μ_x1|Y=A: 4.453125
σ^2_x1|Y=A: 0.9298804946739124
μ_x2|Y=A: 4.5353125
σ^2_x2|Y=A: 0.8659459580965487

Means and Variances for Class B:
μ_x1|Y=B: 7.895555555555556
σ^2_x1|Y=B: 0.7542930628683775
μ_x2|Y=B: 6.408888888888889
σ^2_x2|Y=B: 0.8083308514662165

Posteriors for point (4.65, 6.73):
P(A | x): 0.9983395211507877
P(B | x): 0.001660478849212366

Posteriors for point (4.38, 7.67):
P(A | x): 0.9970421175374431
P(B | x): 0.0029578824625568255


In [31]:
std_devs_A


x_1    0.929880
x_2    0.865946
dtype: float64

In [ ]:
import numpy as np

# replace these values
d = np.array([[2.21, 3.96], [2.34, 3.12], [0.34, 4.0], [1.82, 2.84], [4.56, 5.32], [1.82, 4.31], [2.99, 4.55], [4.18, 4.59], [6.49, 2.8], [4.6, 3.24], [5.97, 2.26], [5.49, 3.75]])
c = np.array([[3.84, 3.84], [4.6, 3.52], [2.26, 3.82]])
r = np.array([[1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]])


def compute_cost(X, centroids, labels):
    cost = 0
    n = len(X)
    for i in range(n):
        k = np.argmax(labels[i])  
        cost += np.linalg.norm(X[i] - centroids[k]) ** 2
    
    return cost


initial_cost = compute_cost(d, c, r)
print(f"Initial Cost: {initial_cost}")


def e_step_kmeans(X, centroids):
    N, K = len(X), len(centroids)
    r = np.zeros((N, K))  
    for i, x in enumerate(X):
        distances = np.linalg.norm(x - centroids, axis=1) 
        closest_cluster = np.argmin(distances)  
        r[i, closest_cluster] = 1  #

    return r

responsibilities = e_step_kmeans(d, c)
print("Responsibility Matrix:")
print(responsibilities)
updated_cost = compute_cost(d, c, responsibilities)
print(f"Updated Cost: {updated_cost}")


Initial Cost: 37.884899999999995
Responsibility Matrix:
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
Updated Cost: 18.756100000000007


In [4]:
import numpy as np

# replace this
d = np.array([[1.79, 3.14], [2.35, 3.25], [2.66, 2.49], [3.06, 4.62], [4.29, 6.55], 
              [2.31, 4.84], [2.93, 4.89], [2.78, 6.91], [3.9, 1.58], [6.88, 3.01], 
              [5.01, 2.93], [5.14, 1.18]])
r = np.array([[1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], 
              [0.0, 1.0, 0.0], [0.0, 1.0, 0.0], [0.0, 1.0, 0.0], [0.0, 1.0, 0.0], 
              [1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0], [1.0, 0.0, 0.0]])

c = np.array([[3.7, 3.41], [3.32, 4.39], [3.75, 3.55]])

def compute_cost(X, centroids, responsibilities):
    cost = 0
    for i, x in enumerate(X):
        assigned_cluster = np.argmax(responsibilities[i]) 
        cost += np.linalg.norm(x - centroids[assigned_cluster]) ** 2
    return cost

def m_step_kmeans(X, responsibilities):
    K = responsibilities.shape[1]
    new_centroids = np.zeros((K, X.shape[1]))
    
    for k in range(K):
        r_k = responsibilities[:, k] 
        denominator = np.sum(r_k) 
        if denominator > 0: 
            new_centroids[k] = np.sum(X * r_k[:, np.newaxis], axis=0) / denominator
        else:
            new_centroids[k] = c[k] 
    
    return new_centroids


updated_centroids = m_step_kmeans(d, r)
updated_cost = compute_cost(d, updated_centroids, r)

print("Updated Centroids:")
print(updated_centroids)
initial_cost = compute_cost(d, c, r)
print(f"Initial Cost: {initial_cost}")
print(f"Cost After M-Step: {updated_cost}")



Updated Centroids:
[[3.475      2.42833333]
 [3.074      5.562     ]
 [6.88       3.01      ]]
Initial Cost: 43.961200000000005
Cost After M-Step: 20.61643333333333
